version: '3.8'

services:
  # Classora.in Application
  classora-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classora-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://classora_user:classora_password@mysql:3306/classora_db
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - classora-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.classora.rule=Host(`classora.in`)"
      - "traefik.http.services.classora.loadbalancer.server.port=3000"

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: classora-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_change_this
      - MYSQL_DATABASE=classora_db
      - MYSQL_USER=classora_user
      - MYSQL_PASSWORD=classora_password_change_this
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - classora-network
    command: --default-authentication-plugin=mysql_native_password

  # Webmin Management Interface
  webmin:
    image: jc21/webmin:latest
    container_name: classora-webmin
    restart: unless-stopped
    ports:
      - "10000:10000"
    environment:
      - WEBMIN_INIT_SSL_ENABLED=1
      - WEBMIN_INIT_REFERERS=classora.in
      - WEBMIN_INIT_PASSWD=admin_password_change_this
    volumes:
      - webmin_data:/etc/webmin
      - webmin_logs:/var/webmin
      - /etc/localtime:/etc/localtime:ro
    networks:
      - classora-network
    depends_on:
      - postfix

  # Postfix Mail Server
  postfix:
    image: catatnight/postfix:latest
    container_name: classora-postfix
    restart: unless-stopped
    hostname: mail.classora.in
    environment:
      - maildomain=classora.in
      - smtp_user=classora:mail_password_change_this
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - postfix_data:/var/mail
      - postfix_logs:/var/log
      - ./postfix/config:/etc/postfix
      - ./postfix/ssl:/etc/ssl/postfix
    networks:
      - classora-network
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  # Dovecot IMAP/POP3 Server
  dovecot:
    image: dovemark/dovecot:latest
    container_name: classora-dovecot
    restart: unless-stopped
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    volumes:
      - postfix_data:/var/mail
      - dovecot_data:/var/lib/dovecot
      - ./dovecot/config:/etc/dovecot
      - ./dovecot/ssl:/etc/ssl/dovecot
    networks:
      - classora-network
    depends_on:
      - postfix

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: classora-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - classora-app
    networks:
      - classora-network

volumes:
  mysql_data:
  webmin_data:
  webmin_logs:
  postfix_data:
  postfix_logs:
  dovecot_data:

networks:
  classora-network:
    driver: bridge
